[project]
name = "quam-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Theo Laudat", email = "theo@quantum-machines.co" }]
requires-python = ">=3.9,<=3.12"
dependencies = ["qualang-tools>=0.19.0", "qualibrate>=0.2.0", "quam>=0.3.10"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["xarray>=2024.7.0"]

[tool.hatch.build.targets.sdist.sources]
"src/quam_builder" = "quam_builder"
